version: '2'

networks:
  public:

  internal:
    internal: true


services:
  fluentd:
    container_name: unms-fluentd
    image: ubnt/unms-fluentd:0.13.2
    restart: always
    networks:
      - public
    ports:
      - "127.0.0.1:24224:24224"
    volumes:
      - /home/unms/app/conf/fluent.conf:/etc/fluent/fluent.conf
      - /home/unms/data/logs:/fluentd/log
    environment:
      - FLUENTD_UID=1000

  redis:
    container_name: unms-redis
    image: redis:3.2.8-alpine
    user: "1000"
    restart: always
    depends_on:
      - fluentd
    networks:
      - internal
    volumes:
      - /home/unms/data/redis:/data/db
    logging:
      driver: fluentd
      options:
        tag: "redis"
        fluentd-async-connect: "true"
    command: "redis-server --appendonly yes --dir /data/db/"

  # we still run postgres as root with stepdown to uid 70 until this issue is fixed
  # https://github.com/docker-library/postgres/issues/264
  # and until it's not required to expose host's /etc/passwd to the container
  # https://hub.docker.com/_/postgres/ (see "Arbitrary --user Notes")
  postgres:
    container_name: unms-postgres
    image: postgres:9.6.1-alpine
    command: postgres -c log_min_duration_statement=500 -c deadlock_timeout=5000
    restart: always
    depends_on:
      - fluentd
    networks:
      - internal
    volumes:
      - /home/unms/data/postgres:/var/lib/postgresql/data/pgdata
    logging:
      driver: fluentd
      options:
        tag: "postgres"
        fluentd-async-connect: "true"
    environment:
      - POSTGRES_DB=unms
      - PGDATA=/var/lib/postgresql/data/pgdata

  rabbitmq:
    container_name: unms-rabbitmq
    image: rabbitmq:3.7.4-alpine
    restart: always
    depends_on:
      - fluentd
    networks:
      - internal
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "rabbitmq"
        fluentd-async-connect: "true"

  unms:
    container_name: unms
    image: ubnt/unms:0.13.2
    restart: always
    depends_on:
      - fluentd
      - redis
      - postgres
    networks:
      - internal
      - public
    volumes:
      - /home/unms/data:/home/app/unms/data
    logging:
      driver: fluentd
      options:
        tag: "unms"
        fluentd-async-connect: "true"
    environment:
      - UNMS_USER_ID=1000
      - DEMO=false
      - NODE_ENV=production
      - HTTP_PORT=8081
      - WS_PORT=8082
      - WS_SHELL_PORT=8083
      - UNMS_WS_API_PORT=8084
      - UNMS_NETFLOW_PORT=2055
      - SSL_CERT=
      - PUBLIC_HTTPS_PORT=443
      - PUBLIC_WS_PORT=
      - HOST_TAG=
      - BRANCH=master
      - http_proxy=
      - HTTP_PROXY=
      - https_proxy=
      - HTTPS_PROXY=
      - no_proxy=
      - NO_PROXY=
      - SECURE_LINK_SECRET=uDluoWGyLv1AFmn2leSQbEV8GKmCWcfyOKrzz9VVX7L23UBAzoFRlF61teShkluPKuRduoYU2NvW1uAzlSwg1QMZmqR5Px1iIVA6
      - CLUSTER_SIZE=auto
    cap_add:
      - NET_ADMIN

  nginx:
    image: ubnt/unms-nginx:0.13.2
    container_name: unms-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"

    networks:
      - public
    volumes:
      - /home/unms/data/cert:/cert

      - /home/unms/data/firmwares:/www/firmwares
    depends_on:
      - unms
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "nginx"
        fluentd-async-connect: "true"
    environment:
      - NGINX_UID=1000
      - SSL_CERT=
      - SSL_CERT_KEY=
      - SSL_CERT_CA=
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - WS_PORT=
      - UNMS_HTTP_PORT=8081
      - UNMS_WS_PORT=8082
      - UNMS_WS_SHELL_PORT=8083
      - UNMS_WS_API_PORT=8084
      - PUBLIC_HTTPS_PORT=443
      - SECURE_LINK_SECRET=uDluoWGyLv1AFmn2leSQbEV8GKmCWcfyOKrzz9VVX7L23UBAzoFRlF61teShkluPKuRduoYU2NvW1uAzlSwg1QMZmqR5Px1iIVA6

  netflow:
    image: ubnt/unms-netflow:0.13.2
    container_name: unms-netflow
    user: "1000"
    restart: always
    ports:
      - "2055:2055/udp"
    networks:
      - internal
      - public
    depends_on:
      - fluentd
      - postgres
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        tag: "netflow"
        fluentd-async-connect: "true"
    environment:
      - UNMS_NETFLOW_PORT=2055
